name: mobile_scanner
description: A Flutter barcode and QR code scanner for Android, iOS & macOS, and web.
version: 7.0.1
#repository: https://github.com/juliansteenbakker/mobile_scanner

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  collection: ">=1.15.0 <2.0.0"
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ">=1.16.0 <2.0.0"
  plugin_platform_interface: ^2.0.2
  web: ">=0.5.1 <2.0.0"
  url_launcher: ^6.3.1
  #cloud_firestore: ^4.17.3
  #uuid: ^4.3.3
  #firebase_core: ^2.30.0
  #firebase_storage: ^11.6.6
  cupertino_icons: ^1.0.6
  #qr_flutter: ^4.1.0
  path_provider: ^2.1.3
  #qr_code_scanner: ^1.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ">=7.0.0 <9.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.steenbakker.mobile_scanner
        pluginClass: MobileScannerPlugin
      ios:
        pluginClass: MobileScannerPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: MobileScannerPlugin
        sharedDarwinSource: true
      web:
        pluginClass: MobileScannerWeb
        fileName: src/web/mobile_scanner_web.dart
